name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    steps:      
      - name: Get CPM
        uses: neacsum/configurator@v0.0.11
        with:
          name: cpm.exe
          url: https://github.com/neacsum/cpm/releases/latest/download/cpm.exe
      
      - name: Build libraries
        run: cpm -v --proto https -u https://github.com/neacsum/mlib.git -r $HOME mlib
        
      - name: Build and run tests
        shell: cmd
        run: |
          %USERPROFILE%\mlib\build.bat tests
        
      - name: Save tests result
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ~/mlib/build/exe/x64/Debug/mlib_tests.xml
